name: Quick Build, Prime Maven Cache

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' 
    - name: Cache Tachyon extensions
      uses: actions/cache@v2
      with:
        path: ~/work/Tachyon/Tachyon/cache/
        key: tachyon-extensions
        restore-keys: tachyon-extensions
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository/*
          !~/.m2/repository/org/tachyon/tachyon/
        key: ${{ runner.os }}-m2
    - name: Build Tachyon with Maven
      run: ant -noinput -buildfile loader/build.xml quick 
